### ISSUE TITLE
Als beheerder van de begraafplaats wil ik een overledene bij een graf registreren

### ISSUE THREAD

**Issue by PatrickCastenmiller** [VNG-Realisatie/Begrafenisplanner#1]
zodat ik weet waar overledenen zijn begraven en welke graven bezet zijn.

**Comment by matthiasoliveiro** [comment]
Is nog niet reviewbaar, frontend moet gedeployed worden.

Na uitleg proto applicatie wordt dit meegenomen in NLdesign

**Comment by PatrickCastenmiller** [comment]
Welke data mag getoond worden (BSN)?

Welke velden moeten worden vastgelegd?

**Comment by PatrickCastenmiller** [comment]
Het is mogelijk een overledene toe te voegen door deze handmatig in te voeren in de registratie. Hiervoor is nog wel een goede invoermogelijkheid met kwaliteitstoetsing (bv. koppeling BRP).

Deze ontwikkelen we samen met de gebruikers. Hierbij moet ook worden bepaald welke gegevens hier bij nodig zijn.
