### ISSUE TITLE
Bug: Als gebruiker verwacht ik processen te kunnen opstarten

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/Begrafenisplanner#102]
Zodat ik de demo kan doorlopen.

Hiervoor moet een menu item worden toegevoegd (heb ik reeds gedaan in datafixtures op het wrc) en verwijzing op de home pagina (heb een home pagina aangemaakt maar daar moet nog html en tekst in).

**Comment by WilcoLouwerse** [comment]
![image](https://user-images.githubusercontent.com/3785488/83237506-4d760280-a195-11ea-8b18-12090d087c0d.png)

**Comment by matthiasoliveiro** [comment]
Hertest OK
