### ISSUE TITLE
Bug: Als gebruiker is het voor mij niet helder wat een verzoek doet

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/Begrafenisplanner#103]
Het zou waarschijnlijk handiger zijn om de beschrijving van een verzoek type weer te geven ipv de datum waarop deze is aangemaakt en bewerkt. In het verlengde hiervan zijn het ook goed zijn om verzoektypen weer te geven met hun icoon (zal een lose user story aanmaken over font awsoe)

**Comment by WilcoLouwerse** [comment]
![image](https://user-images.githubusercontent.com/3785488/83238383-a72afc80-a196-11ea-8bab-caa7265a254a.png)

**Comment by matthiasoliveiro** [comment]
Ik heb iets meer context nodig voor een hertest. Waar kan ik dit zien?

**Comment by matthiasoliveiro** [comment]
met ruben gesproken is inmiddels duidelijk. Hertest OK
