### ISSUE TITLE
Als gebruiker verwacht ik in te loggen als bedrijf en niet als persoon

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/Begrafenisplanner#105]
Ofwel met een spoof van e-herkenning ipf digispoof. Verder verwacht ik dan een bedrijfsversie van het wie bent u informatie blok bij processen

**Comment by PatrickCastenmiller** [comment]
Inloggen is nog even de vraag hoe we dit moeten den. Er komt een nieuwe userstorie die dit goed beschrijft
