### ISSUE TITLE
BUG: 500 Dashboard GRC

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/Begrafenisplanner#116]
Wanneer ik in het dashboard naar een item onder "Grave registration" ga dan krijg ik een 500.

**Comment by matthiasoliveiro** [comment]
![image](https://user-images.githubusercontent.com/36506861/83386735-cc647880-a3eb-11ea-9d20-562d923449b4.png)

error in kwestie:
![image](https://user-images.githubusercontent.com/36506861/83386843-fe75da80-a3eb-11ea-9750-60bbed925ab3.png)

**Comment by rjzondervan** [comment]
Even zien, hier had @ginokok1996 al een fix voor gemaakt, ik zal even kijken of ik die al kan deployen

**Comment by rjzondervan** [comment]
Even nagekeken: er staat nog een PR van Gino open om dit te fixen op het dashboard, dus dit kan ik op dit moment niet even snel deployen.

**Comment by rjzondervan** [comment]
PR van Gino is gedeployed. Aanklikken van een item in grave registration zou nu moeten werken
