### ISSUE TITLE
Als begrafenisondernemer wil ik een datum en tijd kunnen kiezen voor een begrafenis  op een door mij gekozen begraafplaats

### ISSUE THREAD

**Issue by PatrickCastenmiller** [VNG-Realisatie/Begrafenisplanner#12]
Zodat ik zekerheid over plaats en tijd en de rouwkaarten/uitnodigingen kan versturen.

Oplossing:
- [ ] Realiseer back-end zodat je tijd en datum kwijt kan in de API's
- [ ] Realiseer de front-end na aanleiding van de wireframes #21 

**Taken**
- [ ] uitzoeken welke regels er zijn voor het plannen van een begrafenis
- [x] #15 
- [ ] #16 
- [x] #17 
- [x] #18 
- [x] #19 
- [x] #20 
- [ ] #21 
- [ ] Het verzoekcomponent op de begraven omgeving zetten zodat een verzoek kan samengesteld worden die naar een gemeente gestuurd kan worden.

**DoD**
- [ ] Ik plan een begrafenis in op Datum X tijd y en ik krijg hier een bevestiging van.

**Comment by matthiasoliveiro** [comment]
Front-end NLdesign system

**Comment by PatrickCastenmiller** [comment]
Te beantwoorden vragen:
- welke tijden en dagen moeten kunnen worden gebruikt?
- hoe groot zijn de tijdssloten?
- per hoeveel tijd kan het verschuiven (per half uur starten of vaste blokken op de dag)?

**Comment by PatrickCastenmiller** [comment]
Technisch vraagstuk: Deze moet goed aan de agendacomponent worden gehangen, zodat het allemaal goed gaat werken.

**Comment by PatrickCastenmiller** [comment]
In NL design zit nog geen agenda/datumpicker. Matthias onderzoekt of het wel op de planning staat.

**Comment by PatrickCastenmiller** [comment]
Selectie datum en tijd is mogelijk. Er komen twee aanvullende userstories om de informatie goed in het verzoek op te nemen en om de bevestiging te communiceren
