### ISSUE TITLE
Als begrafenisondernemer wil ik handmatig een overledene kunnen invoeren.

### ISSUE THREAD

**Issue by WilcoLouwerse** [VNG-Realisatie/Begrafenisplanner#139]
Zodat ik een overleden kan invoeren als ik dit zou moeten doen omdat ik deze niet kan opzoeken aan de hand van het brp.

Hierbij moet waarschijnlijk dit persoon in het brp component worden opgeslagen zodat deze in het verzoek opgeslagen kan worden?

**Comment by PatrickCastenmiller** [comment]
Is geregeld
