### ISSUE TITLE
Als begrafenisondernemer wil ik dat er een order aangemaakt word voor alle gekozen artikelen bij het plannen van een begravenis.

### ISSUE THREAD

**Issue by WilcoLouwerse** [VNG-Realisatie/Begrafenisplanner#141]
Zodat het mogelijk is om een factuur te genereren en te verzenden.

"Het toepassen van het Ordercomponent."

**Comment by PatrickCastenmiller** [comment]
Is inmiddels geregeld in een andere userstorie. Deze kan worden afgesloten
