### ISSUE TITLE
Het is niet duidelijk waar een wijziging naar toe gaat.

### ISSUE THREAD

**Issue by PatrickCastenmiller** [VNG-Realisatie/Begrafenisplanner#156]
Nu raakt ie zoek, ik kan dit bijvoorbeeld niet vinden in het dashboard van Hoorn.
als er geen referentie is, weet de applicatie natuurlijk ook niet waar die naar toe moet.

**Comment by matthiasoliveiro** [comment]
Klopt de wijziging moet vast zitten aan een hoofdverzoek en ergens logisch komen te staan op het dashboard.
