### ISSUE TITLE
Bij het kiezen van een artikel berekend hij niet de kosten (alleen de kosten van het graf blijven staan)

### ISSUE THREAD

**Issue by PatrickCastenmiller** [VNG-Realisatie/Begrafenisplanner#158]
![image](https://user-images.githubusercontent.com/37135376/90907808-bc997680-e3d3-11ea-9990-0e1c6b236b82.png)

**Comment by matthiasoliveiro** [comment]
Klopt dit is een bug. Het ziet er naar uit dat het artikel niet wordt toegevoegd aan het verzoek. Dus het gaat niet fout bij het rekenen maar bij het toevoegen aan het verzoek.
