### ISSUE TITLE
De begraafplaatsbeheerder kan een geannuleerd verzoek nog zien en bewerken

### ISSUE THREAD

**Issue by PatrickCastenmiller** [VNG-Realisatie/Begrafenisplanner#159]
Je zou verwachten dat als een verzoek geannuleerd is, deze niet zonder meer te bewerken is. Hiervoor zou de indiener eerst het verzoek weer moeten activeren of dit vragen aan de begraafplaatsbeheerder.
Hier moeten we nog afspraken over maken. We kunnen ook afspreken: weg is weg. Dat heeft mijn voorkeur.

Overigens is een uitgangspunt dat een niet ingediend verzoek ook geen sporen achterlaat.

**Comment by matthiasoliveiro** [comment]
Hier hebben wij wat input nodig van de gemeente over hoe dit zou moeten werken.

**Comment by PatrickCastenmiller** [comment]
Het gaat over een niet ingediend verzoek. Als de klant het annuleert, kan je direct de vraag stellen of het ook verwijderd kan worden en dan weggooien. Daarna de mededeling dat het na x dagen definitief wordt verwijderd.
Een geannuleerd verzoek bewaren we anders nog 1 week (lijkt me meer dan genoeg zekerheid).
Dit is verder een verantwoordelijkheid van de klant en niet van de overheid. Als ik thuis een brief begin te schrijven en deze weeggooi en later spijt heb, kan ik dat toch alleen mezelf verwijten.
