### ISSUE TITLE
Als een User wil ik een interface in NL Design

### ISSUE THREAD

**Issue by YorickGroeneveld** [VNG-Realisatie/Begrafenisplanner#16]
We maken gebruik van het NL design system.
Hier voor zijn twee dingen nodig. 

1. een protoapplicatie voor begraven (zit in deze story)
2. een uitleg sessie over NL Design #18 
3. Maken van een wireframe van de front-end #21

**Comment by PatrickCastenmiller** [comment]
Is in de demo werkend getoond
