### ISSUE TITLE
Begrafenisondernemer kan zijn bestellingen zien/ De knop: bekijken werkt niet (doet niets)

### ISSUE THREAD

**Issue by PatrickCastenmiller** [VNG-Realisatie/Begrafenisplanner#161]

**Comment by matthiasoliveiro** [comment]
Pakken we op stond niet in de lijst overigens.

**Comment by matthiasoliveiro** [comment]
gaat om de bekijken knop achter de factuur:

![image](https://user-images.githubusercontent.com/36506861/91276252-92540a00-e781-11ea-90a5-78a031f3df5e.png)

**Comment by PatrickCastenmiller** [comment]
Pakken we op in de ontwerp en bouwweek
