### ISSUE TITLE
Als beheerder wil ik dat, in geval van particulier graf , de aanvrager het bestaande particulier graf  aangeeft op de aanvraag

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/Begrafenisplanner#169]
Zodat ik weer waar iemand moet worden begraven, deze optie speelt alleen bij het (bij) leggen in een particulier graf.

Mogelijke waarde voor dit veld zijn grafnummer of naam van overledene(n) of naam van de huidige rechthebbende.

Dit is dus een property in proces als onderdeel van de begraafplaats stage

**Comment by PatrickCastenmiller** [comment]
Toegevoegd dat het ook kan worden aangegeven door de naam van de hudige rechthebbende in te vullen.

**Comment by rubenvdlinde** [comment]
@matthiasoliveiro testbaar via de route zo als gedefineerd in #191

**Comment by PatrickCastenmiller** [comment]
Gestest en gezien.
