### ISSUE TITLE
Als ondernemer mag ik (wettelijk) de overledene identificeren op de volgende combinaties:

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/Begrafenisplanner#173]
voornaam, achternaam, geb. datum,
geb. datum, geb. datum, achternaam.

https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/master/features/parametercombinaties.feature

Dit gaat dus over het zoeken naar BSN nummer formulier.

**Comment by PatrickCastenmiller** [comment]
We maken het nu niet te ingewikkeld. De beheerders geven aan dat zij nu uitvragen:
- Voornaam overledene
- achternaam overledene
- geboortedatum overledene
- overlijdensdatum overledene

Voorkeur is gewoon BSN opvoeren, misschien samen met naam. We geven dan alleen de informatie als de combinatie klopt. We gaan nog toetsen of hier een privacyrichtlijn wordt overschreden.

**Comment by rjzondervan** [comment]
Dit is nu grafisch gerealiseerd, maar het is nog steeds mogelijk dat er zonder naam wordt gezocht op bsnnummer. Ik ga nog even kijken of ik daar een slimme fix voor kan vinden.

**Comment by rjzondervan** [comment]
Oke, na de volgende deploy kan dit issue in review.

Om te reviewen: ga naar de stap overledene, en stel dan in het formulier 'overledene met bsn' de gegevens 'bsn', 'voorna(a)m(en)' en 'achternaam' in (op dit moment zijn deze nog in het Engels beschreven)
![image](https://user-images.githubusercontent.com/10433082/92398278-87f22280-f128-11ea-8d80-29ebdaba8a7d.png)
Als niet alledrie de gegevens ingevuld worden moet zoeken een foutmelding opleveren, als er wel een kloppende combinatie is ingevoerd zou er een persoon moeten verschijnen die kan worden gekozen.

**Comment by rubenvdlinde** [comment]
@matthiasoliveiro testbaar via die door @rjzondervan hierboven gemelde route

**Comment by PatrickCastenmiller** [comment]
Ziet er goed uit. We halen nu nog op of we BSN mogen gebruiken, eventueeel in combinatie met andere gegevens.
