### ISSUE TITLE
Akte als document kan vervallen

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/Begrafenisplanner#177]
In het begraven procces ik wil hem als medewerker nog steeds een concept kunnen downloaden in het dashboard.

vraag: delen we het document via de planner of direct aan de nabestaande-belanghebbende

**Comment by rubenvdlinde** [comment]
@matthiasoliveiro testbaar door een verzoek in te dienen, op de laatste fase wordt er geen akte meer aangeboden
