### ISSUE TITLE
Als ondernemer wil ik een faktuuradres kunnen invullen zodat de faktuur aan de juiste persoon wordt gericht.

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/Begrafenisplanner#181]
Door het gebruik van een cc/people en cc/address voor de factuur gegevens in een eigen section op de artikelen stage.

Er zijn twee opties:
- aanvrager c.q. begrafenisondernemer (degene die de begrafenis organiseert)
- nabestaande-belanghebbende namens wie het verzoek door de begrafenisondernemer wordt ingediend.

Niet alle gemeenten willen deze optie in beeld brengen. We kiezen ervoor om dit nu niet optioneel in te richten. De indiener van het verzoek kan de keuze zelf maken. Als de ondernemer de factuur wil voorschieten, hoeft ie later toch niet bij de gemeente aan te kloppen als deze zijn geld niet krijgt.

**Comment by rubenvdlinde** [comment]
@matthiasoliveiro testbaar via https://dev.westfriesland.commonground.nu/ptc/process/a8b8ce49-d5db-4270-9e42-4b47902fc817/contactpersoon

Overigens kunnen hete hele factuur verhaal dus gemeentelijk afhankenlijk maken via #191 maar dan moeten we even een lijst krijgen van de gemeenten.

**Comment by PatrickCastenmiller** [comment]
Getest en gezien

**Comment by PatrickCastenmiller** [comment]
Het hele contactformulier etc. moeten we opnieuw ontwerpen. Enige aanpassing voor nu is een JA/NEE vraag of de factuur naar de indiener moet worden gestuurd.
Zie ook #210 en #223 
Hier dus nu niet veel werk in stoppen en issue afronden.
