### ISSUE TITLE
Als gemeente wil ik de startknop in de planner "Aanvragen begrafenis" noemen

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/Begrafenisplanner#184]

**Comment by matthiasoliveiro** [comment]
Op de persoonlijk pagina staat nog de oude titel @YorickGroeneveld

**Comment by YorickGroeneveld** [comment]
Deze is nu ook aangepast. Er staat een pull request open op het ptc hiervoor.

**Comment by rubenvdlinde** [comment]
@matthiasoliveiro testbaar door de home page en de persoonlijk pagina te bekijken
