### ISSUE TITLE
Als klant wil ik een email ontvangen met daarin de bevestiging en alle stukken van mijn begrafenis.

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/Begrafenisplanner#185]

**Comment by rjzondervan** [comment]
Deze even snel uitdiepende: willen we de stukken als bijlagen bij de mail hebben, of is het een mogelijkheid om een link naar de bestanden in te voegen?

**Comment by rjzondervan** [comment]
Grootste probleem van dit issue zit in issue #211, daarom dit issue iets kleiner gemaakt, en #211 groter

**Comment by rjzondervan** [comment]
Issue is nu testbaar: vul bij de contactpersoon je eigen e-mail adres in, en dien het verzoek in. Er volgt nu een e-mail met daarin:
- Ontvangstbevestiging (een beter template volgt nog vanuit issue #167 )
- Orderbevestiging
- Factuur (waarmee ook issue #208 wordt afgehandeld)
