### ISSUE TITLE
Conditioneel weergeven van sections, stages en properties

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/Begrafenisplanner#191]
Zodat ik bepaalde tekst of vragen alleen weergeef in bijzondere gegevens

Bijvoorbeeld factuur informatie alleen bij bepaalde gemeenten, afspraak informatie alleen bij bepaalde begraafplaatsen, documenten alleen bij bepaalde gemeenten, formulier voor contact gegevens overledenen alleen bij een begravenis zonder bsn overledenen etc etc

**Comment by rubenvdlinde** [comment]
Ik heb deze even ongegeneerd boven aan de lijst gezet omdat die bepalend is voor een reeks van andere issues (doe worden hierdoor configuratie vraagstukken).

**Comment by PatrickCastenmiller** [comment]
Voor starten overleg met mij over hoe dit werkt en hoe  we dit inrichten en wat dit voor inspanning is.

**Comment by matthiasoliveiro** [comment]
Besproken en verklaard!

**Comment by rjzondervan** [comment]
hierbij het testscenario voor conditional stages:
Gemeente: Hoorn
Begraafpaats: Keern
Grafsoort: Particulier graf 2 grafruimten 10 jaar

Resultaat: invoerveld voor een grafnaam of -nummer

**Comment by PatrickCastenmiller** [comment]
Getest en gezien.
@rubenvdlinde @rjzondervan is dit de enige situatie waarbij dit werkt? Wat moeten we doen om dit overal in te richten?
