### ISSUE TITLE
Ik wil als gebruiker een contact persoon voor een begrafenis kunnen opgeven.

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/Begrafenisplanner#192]
Zodat ik als gemeente weet wie ik moet bellen over een begrafenis dit is dus de begrafenis leider

**Comment by YorickGroeneveld** [comment]
Added new pull request to fix the non required stage acclamation mark. (Discovered this error after first deployment.)

**Comment by PatrickCastenmiller** [comment]
Kan, maar zie ook #210
