### ISSUE TITLE
Als product owner wil ik het formulier contact persoon kunnen configureren

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/Begrafenisplanner#193]
Zodat ik een contact persoon bijvoorbeeld kan laten bestaan als voornaam, achternaam, geboorte datum, geboorte stad.

**Comment by PatrickCastenmiller** [comment]
Volgens mij gaan deze gegevens over de Overledene zelf.  Zie ook #173

**Comment by rubenvdlinde** [comment]
We hebben nu: 
- Overledenen
- Begravenisleider
- Factuur addres 

Alle 3 zijn contact personen waarvoer we ander dingen willen uitvragen

**Comment by PatrickCastenmiller** [comment]
**Definities van rollen**
. Indiener: degenne die het verzoek instuurt; de organisator van de begrafenis, vaak de begrafenisondernemer.
. Aanvrager: Degene namens wie het verzoek wordt ingediend. Dit is meestal de nabestaande op wiens naam de overeenkomst/akte wordt gezet. Vaak degene die de factuur betaald.
. Rechthebbende: Degene die beschikken mag over een particulier- of familiegraf.

**Comment by rubenvdlinde** [comment]
Simpele test hier hier is nu even of email en telefoon nr nog bij overledenen staan

**Comment by rubenvdlinde** [comment]
@PatrickCastenmiller kan je hier belanghebbende aan toevoegen?

**Comment by PatrickCastenmiller** [comment]
Toegevoegd aan de designdesisions (misschien een rare plaats) en in de opmerking op het bord.

https://github.com/VNG-Realisatie/Begrafenisplanner/blob/master/documenten/Designdecisions.md

**Comment by rubenvdlinde** [comment]
Top, @matthiasoliveiro dit is testbaar via -> https://dev.westfriesland.commonground.nu/ptc/process/a8b8ce49-d5db-4270-9e42-4b47902fc817/overledene de overledenen heeft daar niet langer een email - tel maar wel een geboorte plaats en datum

**Comment by PatrickCastenmiller** [comment]
@rubenvdlinde Hoe kan ik zien of dit is gerealiseerd? Ik zie wel andere velden, maar of sdit voldoet aan de userstorie kan ik niet beoordelen.
