### ISSUE TITLE
Contactgegevens onderaan de pagina leeg laten

### ISSUE THREAD

**Issue by PatrickCastenmiller** [VNG-Realisatie/Begrafenisplanner#194]
Omdat we met meer gemeenten samen deze dienstverlening aanbieden kunnen we dit niet hier neerzetten. 

(gegevens gemeente Hoorn verwijderen)

**Comment by rubenvdlinde** [comment]
Testbaar door naar de omgeving te gaan, er stat geen nieuwsbrief en contactgegevens meer rechtsonder

**Comment by PatrickCastenmiller** [comment]
Gestest en gezien
