### ISSUE TITLE
Als developer wil ik een datamodel hebben voor het grafregistratiecomponent

### ISSUE THREAD

**Issue by rjzondervan** [VNG-Realisatie/Begrafenisplanner#2]
Zodat ik een duidelijke grondslag heb om mijn component op te bouwen.

**Comment by PatrickCastenmiller** [comment]
Nog aandacht voor het goed beschrijven van een graf en de lagen

Moet de GEObeschijving nog 
- het coördinatenstelsel benoemen waarmee gemeten is 
- een Z-waarde bevatten voor de hoogte
