### ISSUE TITLE
Als developer wil ik een WRC(WebResource Component) component in de lucht hebben om een organisatie aan een locatie te koppelen

### ISSUE THREAD

**Issue by YorickGroeneveld** [VNG-Realisatie/Begrafenisplanner#20]
Een organisatie is nodig omdat dit de uitvoerende partij is.

1. beschikbaar maklen op de omgeving
2. configureren naar datamodel #17

**Comment by PatrickCastenmiller** [comment]
Geconstateerd dat het er is.
