### ISSUE TITLE
Als developer wil ik weten wat ik moet doen met de gelaagdheid van een graf

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/Begrafenisplanner#201]
Is dit iets wat we handmatig gaan oppakken of moet het in het datamodel worden mee genomen

**Comment by rubenvdlinde** [comment]
Met @PatrickCastenmiller we gaan gelaagdheid mee nemen in het data model als een begravenis binnen een graf

**Comment by PatrickCastenmiller** [comment]
Hebben we dit voldoende besproken @rubenvdlinde ?
