### ISSUE TITLE
Als developer wil ik een wireframe maken van de front-end

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/Begrafenisplanner#21]
Zodat ik snel feedback kan ophalen bij mijn PO

Is voorwaardelijk voor #16

**Comment by PatrickCastenmiller** [comment]
Kan ik het wireframe ergens vinden (linkje?) zodat ik kan reviewen>

**Comment by WilcoLouwerse** [comment]
[Hier](https://github.com/VNG-Realisatie/Begrafenisplanner/tree/master/documenten/ApplicatieSchetsen) is het wireframe tot nu toe te vinden. Maar we wilde graag in overleg met jou een versie maken die meer gericht is op een burger als gebruiker.
