### ISSUE TITLE
Als beheerder wil ik contactgegevens van de aanvrager en van iemand over de uitvaart

### ISSUE THREAD

**Issue by kimengel** [VNG-Realisatie/Begrafenisplanner#210]

**Comment by rubenvdlinde** [comment]
@matthiasoliveiro testbaar via https://dev.westfriesland.commonground.nu/ptc/process/a8b8ce49-d5db-4270-9e42-4b47902fc817/contactpersoon

**Comment by PatrickCastenmiller** [comment]
Dit is wel erg recht toe recht aan. Wie moet er nu op dit formulier staan. Contactpersoon van??

Er kan hier maar één persoon worden ingevuld. De vraag is om een mogelijkheid te bieden om hier naast een contactpersoon voor communicatie over het invullen van het verzoek ook een contactpersoon die de begrafenis begeleid. (uitvaart begeleider).

**Comment by rubenvdlinde** [comment]
@ginokok1996 oplossings richting maak er een array van zodat er meerdere contact personen kunnen worden toegevoegd

@PatrickCastenmiller wat hier ook gevoels mattig mist is een goed stukje tekst over de hoe en wat van contact personen zou jij die kunnen aanleveren?

**Comment by PatrickCastenmiller** [comment]
We hebben afspraken gemaakt over het toevoegen van de toelichtende teksten. Voor het afronden van deze userstorie is dat niet nodig.

**Comment by PatrickCastenmiller** [comment]
Formulier vraagt nog om aanpassing, maar dat hoeft niet met dit issue. Te zijner tijd voeren we hiervoor een nieuw issue op.
wel aandacht nog voor de vraag naar wie de factuur moet worden gestuurd = #223
