### ISSUE TITLE
Tekst "SED" vervangen door "Stedebroec, Enkhuizen, Drechterland"

### ISSUE THREAD

**Issue by PatrickCastenmiller** [VNG-Realisatie/Begrafenisplanner#214]
In het rol menu gemeente staat SED dit moet zijn Stede Broec, Enkhuizen en Drechterland: ten eerste is het alleen een ambtelijke samenwerking en ten tweede is het maar de vraag of een burger of uitvaartverzorger weet welke gemeenten achter de letters SED zitten.

De gemeenten kunnen apart genoemd worden:

Stedebroec: begraafplaats Rustoord
Enkhuizen: Gemeentelijke begraafplaats
Drechterland: de overige begraafplaatsen van de SED

**Comment by PatrickCastenmiller** [comment]
Deze vraag kreeg ik binnen van Peter Bax. Gaat een zo lange titel problemen geven? Is dit anders op te lossen?

**Comment by PatrickCastenmiller** [comment]
De gemeenten kunnen gewoon apart genoemd worden, even voor de duidelijkheid onder Stede Broec moet dan begraafplaats Rustoord komen,
Enkhuizen de gemeentelijke begraafplaats,
En Drechterland de andere 8.
Met vriendelijke groet,

Peter Bax

**Comment by rubenvdlinde** [comment]
@PatrickCastenmiller hebben we ene lijst van hoe e begraafplaatsen en producten dan moeten worden verdeeld?

**Comment by ginokok1996** [comment]
De gemeentes Drecherland, Stedebroec en Enkhuizen zijn aangemaakt.

**Comment by PatrickCastenmiller** [comment]
De begraafplaatsen zijn niet goed toegedeeld. Dit is natuurlijk wel belangrijk. Ze staan nu allemaal bij Drechterland.

**Comment by ginokok1996** [comment]
@PatrickCastenmiller Zie vraag van @rubenvdlinde hier boven.
Is er een lijst van de verdeling van de begraafplaatsen en producten?

**Comment by PatrickCastenmiller** [comment]
De producten staan in issue #237
