### ISSUE TITLE
Als beheerder wil ik een bericht (email of sms) dat een datum voor een begrafenis is gereserveerd in mijn gemeente, inclusief datum, begraafplaats, ondernemer

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/Begrafenisplanner#219]
Toevoegen aan de begraven service en aantikken vanuit de VSBE ik kom nog even in de lucht over sms

**Comment by PatrickCastenmiller** [comment]
Voorlopig geen SMS. Eerst gewoon inrichten met mail.

**Comment by PatrickCastenmiller** [comment]
@rubenvdlinde Waarom is deze gesloten?

**Comment by PatrickCastenmiller** [comment]
@rubenvdlinde oh sorry, ik zie het al. hij is dubbel. Ik verwijder deze/
