### ISSUE TITLE
(niet) Werking van de agendapagina

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/Begrafenisplanner#222]
In demo-omgeving wordt de datum niet vastgehouden in de weergave (geel vlakje) bij terugkomst.
Ook zijn de andere reserveringen volgens mij niet te zien.

**Comment by PatrickCastenmiller** [comment]
Nagaan of in de dev omgeving de agenda-afspraken worden getoond in het overzicht als bezet. Het lijkt erop dat dat nu niet gebeurd. De afspraak van het verzoek in bewerking wordt wel vastgehouden.
