### ISSUE TITLE
Als beheerder wil ik dat de ondernemer al in het verzoek kan aangeven waar de faktuur naar toe moet (m.u.v. Hoorn)

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/Begrafenisplanner#223]
Duplicaat van #181

**Comment by PatrickCastenmiller** [comment]
Bij een begrafenis in Hoorn, kan ik de factuurcontactpersoon gewoon aangeven.
![image](https://user-images.githubusercontent.com/37135376/92620309-c91e3a00-f2c2-11ea-8319-544c3c982a48.png)

**Comment by rubenvdlinde** [comment]
Ik vermoed dat @rjzondervan het uitzonderen van Hoorn hier als een los issue heeft gezien? Ga ik even ophalen

**Comment by PatrickCastenmiller** [comment]
Laat voor nu de **uitzondering** maar zitten. ALs dit noodzakelijk is pakken we deze weer opnieuw op.
