### ISSUE TITLE
Als beheerder wil ik belanghebbende vervangen door aanvrager/rechthebbende

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/Begrafenisplanner#224]

**Comment by PatrickCastenmiller** [comment]
Dit staat er nog steeds verkeerd in.

![image](https://user-images.githubusercontent.com/37135376/92621578-426a5c80-f2c4-11ea-83c7-ae11ccceb6b6.png)

**Comment by rubenvdlinde** [comment]
Ja hier waren we een pr vergeten mee te nemen in de deploy staat er nu wel goed maar is een bug in geslopen die we nog even moeten fixen.

**Comment by rubenvdlinde** [comment]
![Aanvrager rechthebbende](https://user-images.githubusercontent.com/4021899/92692762-eb589c00-f344-11ea-96b7-871d15d79e6c.PNG)

**Comment by rubenvdlinde** [comment]
Fixed
