### ISSUE TITLE
Als ondernemer wil ik een bestaand graf kunnen gebruiken voor een begrafenis

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/Begrafenisplanner#227]
Vebetering van de werking van #209?

De verwijziging van het graf wil ik op één van de volgende manieren kunnen doen:
- opgeven grafnummer
- Naam van eerder overleden persoon die al in het graf ligt (meestal meer grafplaatsen) + datum van die begrafenis

De controle of dit juist is vindt plaats door de ambtenaar, later in het proces.

**Comment by rubenvdlinde** [comment]
@PatrickCastenmiller deze begrijp ik niet hellemaal

**Comment by PatrickCastenmiller** [comment]
@rubenvdlinde Is dit duidelijker?

**Comment by rjzondervan** [comment]
Deze is nu als voorbeeld gedaan voor de Gemeente Hoorn bij het graftype 'Particulier graf 2 grafruimten 10 jaar'. Als deze wordt geselecteerd is de volgende stap het invoeren van het grafnummer of naam bij het graf.

We vermoeden dat dit bij meerdere grafsoorten voor gaat komen, maar we horen graag welke grafsoorten dit betreft.
