### ISSUE TITLE
Als developer wil ik commits kunnen pushen naar de Begrafenisplanner GitHub vanuit GitKraken

### ISSUE THREAD

**Issue by YorickGroeneveld** [VNG-Realisatie/Begrafenisplanner#23]
![image](https://user-images.githubusercontent.com/47104875/77429713-584d9900-6dda-11ea-929f-a9bc2df2c341.png)
We lopen tegen deze foutmelding aan vanuit GitKraken. Hoogstwaarschijnlijk iets met rechten.

**Comment by WilcoLouwerse** [comment]
@michielverhoef Zou jij ons hiermee verder kunnen helpen?

**Comment by michielverhoef** [comment]
Zelf gebruik ik geen gitkraken, gitbash en de command line tools vind ik zelf veel prettiger, minder rompslomp ook. 

Het bleek dat Gitkraken als applicatie geen rechten had, dat heb ik nu aangezet. Voor de zekerheid heb ik een testje uitgevoerd, dat mogen jullie weggooien als het voor jullie ook werkt.

**Comment by WilcoLouwerse** [comment]
Top! dankjewel.
Dit werkt voor ons nu ook ja
