### ISSUE TITLE
Als gebruiker wil ik kunnen inloggen met mijn eigen acount

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/Begrafenisplanner#230]
Zodat ik er als een realistisch test scenario heb.

**Comment by rubenvdlinde** [comment]
Dan hebben we wel een lijst van gebruikers per gemeente nodig

**Comment by PatrickCastenmiller** [comment]
**Koggenland** 
Lydia Braas <l.braas@koggenland.nl>

**opmeer**
Mark Dekker <mdekker@opmeer.nl>; 

**Medemblik**
Paula Aker <paula.aker@medemblik.nl>; 
Truus Bruinsma-Stapel <truus.bruinsma@medemblik.nl>; 

**SED**
Peter Bax <peter.bax@sed-wf.nl>; 

**Hoorn**
Sjerps, Cees <c.sjerps@hoorn.nl>; 
Kaag - Oud, Esther <e.kaag@hoorn.nl>

**Comment by PatrickCastenmiller** [comment]
@rubenvdlinde   namen toegevoegd

**Comment by rubenvdlinde** [comment]
Testbaar met wachtwoord test1234

**Comment by PatrickCastenmiller** [comment]
Ik  krijg foutmeldingen. 1 keer wel gelukt. Inloggen met dezelfde levert daarna wel een foutmelding op.

![image](https://user-images.githubusercontent.com/37135376/92618166-5ca23b80-f2c0-11ea-85aa-15e900bcfe22.png)

**Comment by PatrickCastenmiller** [comment]
Werkt niet, retour naar in progress

**Comment by rubenvdlinde** [comment]
Yup, zat een bug onder die is opgelost

**Comment by PatrickCastenmiller** [comment]
TOP!! helemaal goed. bedankt
