### ISSUE TITLE
Aanvullen artikelen bij begraafplaatsen SED

### ISSUE THREAD

**Issue by PatrickCastenmiller** [VNG-Realisatie/Begrafenisplanner#237]

**Comment by rubenvdlinde** [comment]
@matthiasoliveiro hebben we een lijst van deze artikelen? Zo ja even toevoegen aan dit issue en toewijzen aan @bbrands02

**Comment by PatrickCastenmiller** [comment]
[mogelijkheden tbv begrafenis.xlsx](https://github.com/VNG-Realisatie/Begrafenisplanner/files/5199591/mogelijkheden.tbv.begrafenis.xlsx)
Bijlage met de artikelen van de SED

**Comment by matthiasoliveiro** [comment]
#183 moet eerst worden gedaan voordat we deze goed kunnen oplossen.

**Comment by PatrickCastenmiller** [comment]
Die voorwaarde is hier niet. DIt is een actie die jullie moeten uitvoeren. #183 gaat over een mogelijkheid dat een applicatiebeheerder van de gemeente dit zelf kan doen.
Nu gaat het erom dat in de plannner de jyuiste artikelen bij elke begraafplaats staan.

**Comment by matthiasoliveiro** [comment]
Door een nieuw inzicht moeten we overstappen van productcatalogi per begraafplaats naar product groepen per begraafplaats.
In het Datamodel kon een product bestaan bij of 1 gemeente of 1 begraafplaats. Het voortschrijdend inzicht is dat producten leidend zijn en dus voor kunnen komen bij meerdere begraafplaatsen maar niet perse bij alle begraafplaatsen. Dit treed toevallig op bij de SED gemeenten (rijdende baar is alleen niet beschikbaar op rustoord). Ook dat het zelfde product meerdere prijzen heeft binnen de zelfde gemeente moeten we hier oplossen. Het opvoeren van producten is niet het issue hier maar het juist zichtbaar maken van de producten is even een uitdaging. #237 gaat over het opvoeren van de producten en #183 gaat inderdaad over dat het instellen überhaupt kan. Misschien moeten we dat issue splitsen? @PatrickCastenmiller

**Comment by matthiasoliveiro** [comment]
[mogelijkheden.tbv.begrafenis.xlsx](https://github.com/VNG-Realisatie/Begrafenisplanner/files/5244248/mogelijkheden.tbv.begrafenis.xlsx)
