### ISSUE TITLE
Als gebruiker wil ik een overzichtelijk contact formulier

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/Begrafenisplanner#241]
Zodat ik meer overzicht heb op wat ik moet invullen

Hierbij is de geachte dat meerdere velden op een rij moeten staan, is het zo dat dat bepaalde velden op een rij vanuit configuratie niet worden weergegeven en moeten de colls van de overige velden breder worden.

Op één rij horen

- voornaam, TUSSENVOEGSEL, achternaam
- straatnaam, huisnummer, toevoeging
- postcode, stad
- Email, telefoon nummer
- Geboorte datum, Geboorte stad

![Opkuizen contact formulier](https://user-images.githubusercontent.com/4021899/92682150-dfaeaa80-f32f-11ea-9966-71000a95bb56.PNG)

**Comment by PatrickCastenmiller** [comment]
Het hele contactformulier etc. moeten we opnieuw ontwerpen. Enige aanpassing voor nu is een JA/NEE vraag of de factuur naar de indiener moet worden gestuurd.
Zie ook #210 en #223 en #181 
Hier dus nu niet veel werk in stoppen en issue afronden.
