### ISSUE TITLE
Als beheerder wil ik een verplicht veld voor standaard/afwijkende kistmaten (ja/nee) en evt maten zodat het juiste maat graf wordt gegraven

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/Begrafenisplanner#250]
Dus er moet een ja nee vraag worden gesteld, daar moet een antwoord op worden gegeven

Ja, de kist valt binnen de standaard afmetingen van ... bij ...

Nee, de kist is groter dan de standaard afmetingen van ... bij ....

Als het antwoord op de vraag nee is dan moet er een toelichtingsveld worden getoond (input text) waarin de ebgravenis ondernemer kan opgeven wat de maten dan wel zijn. 

@PatrickCastenmiller heb jij de standaard kost maten ?

**Comment by PatrickCastenmiller** [comment]
Ik zorg voor een ontwerpje.
