### ISSUE TITLE
Als product owner wil ik vastleggen dat de factuur is afgeboekt door de financiële administratie

### ISSUE THREAD

**Issue by rjzondervan** [VNG-Realisatie/Begrafenisplanner#271]
Zodat ik kan bepalen dat het graf aan de gemeente vervalt

Oplossingsrichting: status opnemen in het BC voor oninbare facturen
Het vervallen van de rechten is opgenomen in #272 

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [x] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [x] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by matthiasoliveiro** [comment]
uitvragen hoe we dit gaan vastleggen en hoe de vervolgstappen vorm te geven.

**Comment by matthiasoliveiro** [comment]
@rjzondervan wil je de oplossingsrichting toevoegen?

**Comment by matthiasoliveiro** [comment]
vervalt
