### ISSUE TITLE
Als begrafenisondernemer wil ik een belanghebbende in kunnen stellen voor de overledene

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/Begrafenisplanner#28]
Zodat de correspondentie naar die persoon gaat ipv het adres van de overledene

**Comment by PatrickCastenmiller** [comment]
Dit is ook een vraag van de landelijke projectgroep die bezig is met levensgebeurtenis Overlijden. Zij willen graag een contactpersoon met wie de overheid lopende zaken of voorzieningen kan regelen.

**Comment by PatrickCastenmiller** [comment]
https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/issues/607

**Comment by rubenvdlinde** [comment]
Voorstel wijzing datamodel van belanghebbende een koppelobject maken in lijn zrc en vrc waarop we kunnen tijdreizen.
