### ISSUE TITLE
Als begrafenisondernemer wil ik een grafsoort kunnen kiezen

### ISSUE THREAD

**Issue by PatrickCastenmiller** [VNG-Realisatie/Begrafenisplanner#34]
Zodat de nabestaanden hun voorkeur kunnen kiezen

Denk hierbij aan familiegraf, algemeen graf, Joods Graf, etc.

Hier moet dit gefilterd kunnen worden aan de hand van de geselecteerde begraafplaats.

Hierbij word het datamodel aangepast zodat grave_types niet meer in het grc staan maar naar het pdc verplaatsen.

**Comment by rubenvdlinde** [comment]
We willen dus vanuit een begraafplaats kunnen vragen welke grafsoorten er voor die begraafplaats beschikbaar zijn

**Comment by matthiasoliveiro** [comment]
Sprint review: Voeg alle grafsoorten per gemeente toe aan alle bij behoorden begraafplaatsen en laat bij een Hoornse begraafplaats er 1 weg.
