### ISSUE TITLE
Overleden persoon toevoegen aan BRP mock

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/Begrafenisplanner#36]
De huidige BRP mock gaat uit van levende personen. Dat is niet volledig. Voor dit project moeten we de status "Overleden" toevoegen.

We moeten uitzoeken in de documentatie van haal centraal waar dat zou moeten zitten.

**Comment by matthiasoliveiro** [comment]
We gaan nu uit van een status veld in Haalcentraal waar in aangegeven wordt dat een persoon is overleden

**Comment by PatrickCastenmiller** [comment]
Op de github van Haal centraal is een isue hierover:
https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/issues/607

Opvragen van Overleden persoon is gewoon mogelijk. 
Oude overleden personen staan niet allemaal nog in de BRP. Recente blijven wel opgenomen.

**Comment by matthiasoliveiro** [comment]
Dan is deze gewoon ready, we moeten wel even kijken hoe je afleid dat de persoon is overleden.

**Comment by PatrickCastenmiller** [comment]
> Historisch

leden
