### ISSUE TITLE
Als developer wil ik gebruikmaken van het PDC component

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/Begrafenisplanner#38]
Zodat het mogelijk is om producten aan begravenissen te kunnen hangen 

Dit is tevens voorwaardelijk voor het opmaken van de rekening/factuur

**Comment by PatrickCastenmiller** [comment]
Doel: Is beschikbaar in het ecosysteem

**Comment by rjzondervan** [comment]
Oke: dit is reviewbaar door te controleren of het ordercomponent beschikbaar is op https://pdc.dev.westfriesland.commonground.nu
