### ISSUE TITLE
Als developer wil ik een producten- en dienstencatalogus

### ISSUE THREAD

**Issue by rjzondervan** [VNG-Realisatie/Begrafenisplanner#4]
Om specifieke gegevens over producten vast te kunnen leggen

**Comment by rjzondervan** [comment]
Deze is reeds beschikbaar als https://pdc.dev.begraven.zaakonline.nl/

**Comment by PatrickCastenmiller** [comment]
Zoals afgesproken gaat deze zonder verder testen naar "done". Bij eerste gebruik ervaren we of het echt klaar is en als er problemen zijn, formuleren we nieuwe issues.
