### ISSUE TITLE
Als beheerder van de begraafplaats wil ik een overzicht van alle geplande begrafenissen per begraafplaats

### ISSUE THREAD

**Issue by PatrickCastenmiller** [VNG-Realisatie/Begrafenisplanner#44]
Zodat ik weet wanneer op welke begraafplaats door wie een begrafenis is georganiseerd.
Op het dashboard.

**Comment by rubenvdlinde** [comment]
Weergave in dashboard.

**Comment by PatrickCastenmiller** [comment]
Het overzicht is beschikbaar. Het is echter geen goed toegankelijke lijst en geeft ook geen goed overzicht van de planning van een begraafplaats. 

Dit ontwikkelen we samen met de beheerders in nieuwe userstories.
