### ISSUE TITLE
Als developer wil ik een ordercomponent

### ISSUE THREAD

**Issue by rjzondervan** [VNG-Realisatie/Begrafenisplanner#5]
Om specifieke gegevens over orders vast te kunnen leggen

**Comment by rjzondervan** [comment]
Deze is reeds beschikbaar als https://orc.dev.begraven.zaakonline.nl/

**Comment by PatrickCastenmiller** [comment]
Zoals afgesproken gaat deze zonder verder testen naar "done". Bij eerste gebruik ervaren we of het echt klaar is en als er problemen zijn, formuleren we nieuwe issues.
