### ISSUE TITLE
Als developer wil ik een locatiecomponent

### ISSUE THREAD

**Issue by rjzondervan** [VNG-Realisatie/Begrafenisplanner#6]
Om specifieke gegevens over locaties vast te kunnen leggen

**Comment by rjzondervan** [comment]
Deze is reeds beschikbaar als https://lc.dev.begraven.zaakonline.nl/

**Comment by PatrickCastenmiller** [comment]
Zoals afgesproken gaat deze zonder verder testen naar "done". Bij eerste gebruik ervaren we of het echt klaar is en als er problemen zijn, formuleren we nieuwe issues.
