### ISSUE TITLE
Bug: Logo wordt niet weergegeven

### ISSUE THREAD

**Issue by rjzondervan** [VNG-Realisatie/Begrafenisplanner#77]

**Comment by PatrickCastenmiller** [comment]
Logo staat op 
[documenten/artwork/logo Westfriesland vector.svg
](url)

**Comment by PatrickCastenmiller** [comment]
Logo staat op 

documenten/artwork/logo Westfriesland vector.svg

**Comment by PatrickCastenmiller** [comment]
@WilcoLouwerse en @YorickGroeneveld Op zowel de planner als op het dashboard is deze niet aanwezig.

**Comment by rjzondervan** [comment]
Is inmiddels gedeployed. @PatrickCastenmiller als het niet wordt geladen, check ook even met Control+F5 ;)

**Comment by PatrickCastenmiller** [comment]
Ik zie nog geen logo op het dashboard. Zou dat wel moeten?
