### ISSUE TITLE
Als begrafenisondernemer wil ik de door mij gekozen gegevens van het begrafenis verzoek proces op het scherm zien

### ISSUE THREAD

**Issue by WilcoLouwerse** [VNG-Realisatie/Begrafenisplanner#78]
Zodat ik kan zien wat ik al gedaan heb in het begraven proces.

(Zoals de vorige versie van de begrafenisplanner dat ook had)

**Comment by PatrickCastenmiller** [comment]
Klopt, deze zijn nu op de pagina te zien.  Op sommige pagina's lijken ze te ontbreken. Door een foutmelding Kan ik het nu niet bij elke processtap controleren. Laat hem dus nog even staan en review deze later.

**Comment by PatrickCastenmiller** [comment]
Werkt nu goed.
