### ISSUE TITLE
Als developer wil ik een brp-component

### ISSUE THREAD

**Issue by rjzondervan** [VNG-Realisatie/Begrafenisplanner#8]
Om gegevens van personen op te halen.

**Comment by rjzondervan** [comment]
Reeds in mock beschikbaar als https://brp.dev.begraven.zaakonline.nl/

**Comment by PatrickCastenmiller** [comment]
Zoals afgesproken gaat deze zonder verder testen naar "done". Bij eerste gebruik ervaren we of het echt klaar is en als er problemen zijn, formuleren we nieuwe issues.
