### ISSUE TITLE
Als gebruiker wil ik aan het einde van mijn proces een bevestigings pagina

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/Begrafenisplanner#80]
zodat ik weet wat ik heb opgegeven heb, en vertrouwen krijg in het procces

**Comment by rubenvdlinde** [comment]
Conform processen verhaal in de proto applicatie

**Comment by matthiasoliveiro** [comment]
Hertest NOK na Indienen verwacht ik feedback dat mijn verzoek is ingediend en een korte beschrijving van wat er nu gaat gebeuren (De begraafplaats neemt het in behandeling en laat het u zo snel mogelijk weten. oid)

**Comment by PatrickCastenmiller** [comment]
Is aanwezig
