### ISSUE TITLE
Bug: Als gebruiker wil ik kunnen inloggen via de inlog knop

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/Begrafenisplanner#85]
Zodat ik geen foutmeldig krijg

![inlogeen op dashboard geeft een foutmelding](https://user-images.githubusercontent.com/4021899/83221124-417a4880-a175-11ea-88c7-becce546a711.PNG)

**Comment by matthiasoliveiro** [comment]
Hertest OK
