### ISSUE TITLE
Bug: Als gebruiker wil ik de complete flow kunnen lopen zonder dat er 500 meldigen verschijnen

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/Begrafenisplanner#86]
Zodat ik er op kan vertrouwen dat het proces werkt 

![500 onder opslaan bij begraven](https://user-images.githubusercontent.com/4021899/83221203-7090ba00-a175-11ea-8452-2225d2454755.PNG)

**Comment by matthiasoliveiro** [comment]
Beetje lastig te testen. Maar geen 500's bij de happy flow.
