### ISSUE TITLE
Bug: Als gebruiker wil ik dat de knopjes goed zijn uitgelijnd

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/Begrafenisplanner#87]
Zodat ik niet zeeziek wordt

![opslaan knopjes slecht uitgelijnd](https://user-images.githubusercontent.com/4021899/83221228-82725d00-a175-11ea-9e73-1fc6d2f6f26b.PNG)

**Comment by matthiasoliveiro** [comment]
Hertest OK
