### ISSUE TITLE
Bug: Als gebruiker wil ik een onhoudbare terugkoppeling op mijn verzoek

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/Begrafenisplanner#88]
In plaats van de UUID verwacht ik dus de reference in de weergave
![verzoek terugkoppelen aan de hand van reference](https://user-images.githubusercontent.com/4021899/83221314-c6fdf880-a175-11ea-8657-8b56c4f486d6.PNG)

**Comment by rjzondervan** [comment]
Hier lijkt de commonground service in de bundle schuldig te zijn, ik tik deze dus even naar mezelf over

**Comment by rjzondervan** [comment]
Oke, oorzaak gevonden, bespreek straks even met Ruben wat de handigste oplossing is

**Comment by matthiasoliveiro** [comment]
hertest OK
