### ISSUE TITLE
Als developer wil ik een component met rvig-tabellen

### ISSUE THREAD

**Issue by rjzondervan** [VNG-Realisatie/Begrafenisplanner#9]
Om gegevens van gemeenten op te halen.

**Comment by rjzondervan** [comment]
Reeds beschikbaar op https://ltc.dev.begraven.zaakonline.nl

**Comment by PatrickCastenmiller** [comment]
Zoals afgesproken gaat deze zonder verder testen naar "done". Bij eerste gebruik ervaren we of het echt klaar is en als er problemen zijn, formuleren we nieuwe issues.
