### ISSUE TITLE
Bug: Als gebruiker verwacht ik een homepage met wat algemene informatie over de demo

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/Begrafenisplanner#90]
zodat ik weet wat hier wordt gedemod en wat ik daar mee kan

**Comment by WilcoLouwerse** [comment]
![image](https://user-images.githubusercontent.com/3785488/83237731-ad6ca900-a195-11ea-975b-660292d7a07b.png)

**Comment by matthiasoliveiro** [comment]
Hertest OK
