### ISSUE TITLE
Bug: Als developer verwacht ik geen hardcoded UUID's in de code

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/Begrafenisplanner#91]
zodat ik flexibel met instellingen kan omgaan

**Comment by PatrickCastenmiller** [comment]
@matthiasoliveiro Wie kan beoordelen of dit inderdaad is opgelost?

**Comment by matthiasoliveiro** [comment]
Dit is een code review item. @rubenvdlinde kan dit beoordelen.
