### ISSUE TITLE
Bug: Als gebruiker wil ik geen verzoek kunnen opstarten als ik niet ben ingelogd

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/Begrafenisplanner#94]
Zodat ik niet vastloopt in de flow, met andere woorden de start verzoek knop niet weergeven als een gebruiker niet is ingelogd

**Comment by WilcoLouwerse** [comment]
Nog niet in online deploy aanwezig.
https://github.com/WilcoLouwerse/Begrafenisplanner-application-NLDesign/commit/f205e8bbee5e03eec57c6d2985070def18daa076

**Comment by matthiasoliveiro** [comment]
hertest OK
