### ISSUE TITLE
Als gebruiker verwacht ik een indienen pagina aan het einde van mijn verzoek

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/Begrafenisplanner#96]
Zodat er een duidelijke verschil is tussen het maken en indienen van een verzoek, en ik zicht heb op welke waardes ik indien.

@rjzondervan hiervoor was vanuit het corona verhaal een pagina beschikbaar maar deze is volgensmij nog niet geimplementeerd

**Comment by matthiasoliveiro** [comment]
Hertest OK
