### ISSUE TITLE
Bug: Als gebruiker verwacht ik niet dat er test data in de weergave staat

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/Begrafenisplanner#97]
Zodat ik het idee heb met een volwassen applicatie te maken te hebben

![Cashe staat in beeld](https://user-images.githubusercontent.com/4021899/83221877-5eb01680-a177-11ea-8ed8-fa5f72ec1948.PNG)

**Comment by matthiasoliveiro** [comment]
Hertest OK
