### ISSUE TITLE
Bug: Logo westfriesland

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/Begrafenisplanner#99]
Er wordt nu wel een gele achtergrond toegepast maar volgensmij had west-friesland ook nog een wapen

![Cashe staat in beeld](https://user-images.githubusercontent.com/4021899/83222087-bd759000-a177-11ea-917d-b9a9c1f8d1d4.PNG)

**Comment by WilcoLouwerse** [comment]
![image](https://user-images.githubusercontent.com/3785488/83238085-371c7680-a196-11ea-8d64-273be4e5e4e8.png)
Hierbij hebben wij nog wat ondersteuning nodig

**Comment by PatrickCastenmiller** [comment]
Hij is er
